name: release

on:
  push:
    branches:
      - master

jobs:
  build-release:
    name: Build app release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Packages
        run:
          npm install
      - name: Build application
        run:
          npm run build
      - uses: actions/cache@v2
        id: save-build
        with:
          path: ./*
          key: ${{ github.sha }}
  push-release:
    name: Push release artifact
    runs-on: ubuntu-latest
    needs: build-release
    environment: staging
    env:
        S3_BUILDS_BUCKET: ${{ secrets.S3_BUILDS_BUCKET }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Create artifact
        run:
          zip -r artifact.zip ./build
      - name: Push artifact
        run:
          aws s3 cp artifact.zip s3://$S3_BUILDS_BUCKET
